version: "2.4"

services:
  # MongoDB
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db

  malanghub:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - .:/app

# Volumes
volumes:
  mongo-volume:

networks:
  malanghub_network:
