apiVersion: apps/v1
kind: Deployment
metadata:
  name: malanghub-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malanghub-api
  template:
    metadata:
      labels:
        app: malanghub-api
    spec:
      containers:
        - name: malanghub-api
          image: registry.digitalocean.com/fahmialfareza/malanghub-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "512Mi"
              cpu: "256m"
            requests:
              memory: "256Mi"
              cpu: "128m"
          livenessProbe:
            tcpSocket:
              port: 4000 # The port to check
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 4000 # The port to check
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: malanghub-api-srv
spec:
  selector:
    app: malanghub-api
  ports:
    - name: malanghub-api
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: malanghub-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: malanghub-api-depl
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 # Target 80% CPU utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 # Target 70% Memory utilization
