# fly.toml app configuration file generated for malanghub-backend on 2023-07-16T17:28:04+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "malanghub-backend"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
