// USER
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const USER_GET_PROFILE = "USER_GET_PROFILE";
export const USER_GET_PROFILE_ERROR = "USER_GET_PROFILE_ERROR";
export const USER_AUTH_ERROR = "USER_AUTH_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_CLEAR_ERRORS = "USER_CLEAR_ERRORS";
export const USER_UPDATE_PROFILE = "USER_UPDATE_PROFILE";
export const USER_UPDATE_PROFILE_ERRORS = "USER_UPDATE_PROFILE_ERRORS";

// NEWS CATEGORY
export const GET_ALL_NEWS_CATEGORIES = "GET_ALL_NEWS_CATEGORIES";
export const ADD_NEWS_CATEGORY = "ADD_NEWS_CATEGORY";
export const SELECT_NEWS_CATEGORY = "SELECT_NEWS_CATEGORY";
export const UPDATE_NEWS_CATEGORY = "UPDATE_NEWS_CATEGORY";
export const DELETE_NEWS_CATEGORY = "DELETE_NEWS_CATEGORY";
export const GET_NEWS_BY_CATEGORY = "GET_NEWS_BY_CATEGORY";
export const NEWS_CATEGORIES_ERROR = "NEWS_CATEGORIES_ERROR";
export const NEWS_CATEGORIES_CLEAR_ERROR = "NEWS_CATEGORIES_CLEAR_ERROR";

// NEWS TAGS
export const GET_ALL_NEWS_TAGS = "GET_ALL_NEWS_TAGS";
export const ADD_NEWS_TAG = "ADD_NEWS_TAG";
export const SELECT_NEWS_TAG = "SELECT_NEWS_TAG";
export const UPDATE_NEWS_TAG = "UPDATE_NEWS_TAG";
export const DELETE_NEWS_TAG = "DELETE_NEWS_TAG";
export const GET_NEWS_BY_TAG = "GET_NEWS_BY_TAG";
export const CLEAR_ALL_NEWS_TAGS = "CLEAR_ALL_NEWS_TAGS";
export const NEWS_TAGS_ERROR = "NEWS_TAGS_ERROR";
export const NEWS_TAGS_CLEAR_ERROR = "NEWS_TAGS_CLEAR_ERROR";

// NEWS DRAFTS
export const GET_ALL_NEWS_DRAFTS = "GET_ALL_NEWS_DRAFTS";
export const GET_MY_DRAFTS = "GET_MY_DRAFTS";
export const ADD_NEWS_DRAFT = "ADD_NEWS_DRAFT";
export const SELECT_NEWS_DRAFT = "SELECT_NEWS_DRAFT";
export const UPDATE_NEWS_DRAFT = "UPDATE_NEWS_DRAFT";
export const UPDATE_NEWS_DRAFT_APPROVED = "UPDATE_NEWS_DRAFT_APPROVED";
export const DELETE_NEWS_DRAFT = "DELETE_NEWS_DRAFT";
export const NEWS_DRAFTS_ERROR = "NEWS_DRAFTS_ERROR";
export const NEWS_DRAFTS_CLEAR_ERROR = "NEWS_DRAFTS_CLEAR_ERROR";

// NEWS
export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const GET_RELATED_NEWS = "GET_RELATED_NEWS";
export const GET_MY_NEWS = "GET_MY_NEWS";
export const GET_ONE_NEWS = "GET_ONE_NEWS";
export const DELETE_NEWS = "DELETE_NEWS";
export const NEWS_ERROR = "NEWS_ERROR";
export const NEWS_CLEAR_ERROR = "NEWS_CLEAR_ERROR";

// NEWS COMMENTS
export const GET_NEWS_COMMENTS_BY_NEWS = "GET_NEWS_COMMENTS_BY_NEWS";
export const CREATE_NEWS_COMMENT = "CREATE_NEWS_COMMENT";
export const SELECT_NEWS_COMMENT = "SELECT_NEWS_COMMENT";
export const CREATE_NEWS_COMMENT_BY_COMMENT = "CREATE_NEWS_COMMENT_BY_COMMENT";
export const NEWS_COMMENT_ERROR = "NEWS_COMMENT_ERROR";
export const NEWS_COMMENT_CLEAR_ERROR = "NEWS_COMMENT_CLEAR_ERROR";

// LOADING
export const SET_LOADING = "SET_LOADING";

// LAYOUT
export const SET_THEME = "SET_THEME";
export const SET_ACTIVE_LINK = "SET_ACTIVE_LINK";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
